version: "3.8"

services:
  scraper:
    build: ./
    image: gov-scrape:latest
    volumes:
      - ./feeds:/usr/src/app/feeds
      - ./logs:/usr/src/app/logs
    stdin_open: true
    networks:
      - gov-scrape
    restart: always
    environment:
      SPLASH_IP: splash:8050
  splash:
    image: scrapinghub/splash:latest
    networks:
      - gov-scrape

networks:
  gov-scrape:
