version: "3.8"

services:
  gov-scrape:
    image: callumskeet/gov-scrape:slim
    volumes:
      - ./feeds:/gov-scrape/feeds
      - ./logs:/gov-scrape/logs
      - ./httpcache:/gov-scrape/.scrapy/httpcache
    stdin_open: true
    networks:
      - gov-scrape
    restart: "no"
    environment:
      SPLASH_IP: splash:8050
  splash:
    image: scrapinghub/splash:master
    networks:
      - gov-scrape

networks:
  gov-scrape:
